# Generated by Django 3.2 on 2021-04-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='goal_type',
            field=models.CharField(default='weekly', max_length=50),
        ),
        migrations.AddField(
            model_name='work',
            name='work_type',
            field=models.CharField(default='day', max_length=50),
        ),
    ]
