# Generated by Django 3.2 on 2021-04-25 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210424_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='goal_type',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='work',
            name='work_type',
            field=models.CharField(max_length=200),
        ),
    ]
